:concurrency: 5
:queues:
  - default

:timeout: 25
:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid

:redis:
  url: redis://redis:6379/0
  namespace: sidekiq

:scheduler:
  :schedule:
    import_market_data_job:
      cron: "0 22 * * 2"
      class: ImportMarketDataJob

    export_prices_to_csv:
      cron: "0 23 * * 2"
      class: ExportPricesToCsv
